# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: cywhat-halo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Vercel
      uses: ngduc/vercel-deploy-action@master
      with:
          vercel-cli: vercel
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORGID}}
          vercel-project-id: ${{ secrets.PROJECTID}}
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: cywhat-halo
      run: java -jar ./halo-1.4.16.jar
    - name: Deploy to Vercel
      run: vercel --token ${VERCEL_TOKEN} --prod
      env:
         VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
         VERCEL_PROJECT_ID: ${{ secrets.PROJECTID }}
         VERCEL_ORG_ID: ${{ secrets.ORGID }}
